/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.Aco;
import classes.Pokedex;
import classes.Pokemon;
import enums.ETipo;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis Guilherme
 */
public class TelaPokedex extends javax.swing.JFrame {

    public Pokedex pokedex;
    
    public TelaPokedex() {
        initComponents();
        btcadastrar.setContentAreaFilled(false);
        pokedex = new Pokedex();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grSelecao = new javax.swing.ButtonGroup();
        btcadastrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taInfo = new javax.swing.JTextArea();
        rbTodos = new javax.swing.JRadioButton();
        rbNome = new javax.swing.JRadioButton();
        rbTipo = new javax.swing.JRadioButton();
        rbCodigo = new javax.swing.JRadioButton();
        btBuscar = new javax.swing.JButton();
        tfBuscar = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        lbTipo = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        tfNome = new javax.swing.JTextField();
        lbPeso = new javax.swing.JLabel();
        lbAltura = new javax.swing.JLabel();
        tfAltura = new javax.swing.JTextField();
        lbAtaque = new javax.swing.JLabel();
        tfAtaque = new javax.swing.JTextField();
        lbForca = new javax.swing.JLabel();
        tfForca = new javax.swing.JTextField();
        lbDefesa = new javax.swing.JLabel();
        tfDefesa = new javax.swing.JTextField();
        lbAgilidade = new javax.swing.JLabel();
        tfAgilidade = new javax.swing.JTextField();
        tfPeso = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        lbImagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pokédex");
        setMaximumSize(new java.awt.Dimension(761, 536));
        setPreferredSize(new java.awt.Dimension(761, 536));
        setResizable(false);
        getContentPane().setLayout(null);

        btcadastrar.setBackground(new java.awt.Color(192, 13, 13));
        btcadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cruz.png"))); // NOI18N
        btcadastrar.setBorder(null);
        btcadastrar.setBorderPainted(false);
        btcadastrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cruz2.png"))); // NOI18N
        getContentPane().add(btcadastrar);
        btcadastrar.setBounds(240, 380, 110, 110);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        taInfo.setEditable(false);
        taInfo.setBackground(new java.awt.Color(51, 255, 51));
        taInfo.setColumns(20);
        taInfo.setRows(5);
        taInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane1.setViewportView(taInfo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(440, 90, 300, 170);

        grSelecao.add(rbTodos);
        rbTodos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbTodos.setSelected(true);
        rbTodos.setText("Todos");
        rbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTodosActionPerformed(evt);
            }
        });
        getContentPane().add(rbTodos);
        rbTodos.setBounds(670, 10, 59, 23);

        grSelecao.add(rbNome);
        rbNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbNome.setText("Nome");
        rbNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNomeActionPerformed(evt);
            }
        });
        getContentPane().add(rbNome);
        rbNome.setBounds(440, 10, 57, 23);

        grSelecao.add(rbTipo);
        rbTipo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbTipo.setText("Tipo");
        rbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTipoActionPerformed(evt);
            }
        });
        getContentPane().add(rbTipo);
        rbTipo.setBounds(600, 10, 49, 23);

        grSelecao.add(rbCodigo);
        rbCodigo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbCodigo.setText("Código");
        rbCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(rbCodigo);
        rbCodigo.setBounds(520, 10, 63, 23);

        btBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btBuscar);
        btBuscar.setBounds(660, 50, 80, 23);

        tfBuscar.setEnabled(false);
        tfBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(tfBuscar);
        tfBuscar.setBounds(440, 50, 210, 30);

        jPanel1.setBackground(new java.awt.Color(192, 13, 13));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        lbNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbNome.setText("Nome:");

        lbTipo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbTipo.setText("Tipo:");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aço", "Água", "Dragão", "Elétrico", "Fada", "Fantasma", "Fogo", "Gelo", "Grama", "Inseto", "Lutador", "Normal", "Pedra", "Psiquico", "Terra", "Veneno", "Voador" }));
        cbTipo.setSelectedIndex(-1);

        lbPeso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbPeso.setText("Peso:");

        lbAltura.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbAltura.setText("Altura:");

        lbAtaque.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbAtaque.setText("Ataque:");

        lbForca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbForca.setText("Força:");

        lbDefesa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbDefesa.setText("Defesa:");

        lbAgilidade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbAgilidade.setText("Agilidade:");

        btCadastrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btRemover.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btRemover.setText("Remover");
        btRemover.setEnabled(false);

        btEditar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btEditar.setText("Editar");
        btEditar.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbDefesa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfDefesa, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAgilidade)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbPeso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbAtaque, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfAtaque, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                    .addComponent(tfPeso))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbForca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfForca, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfAgilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btCadastrar)
                .addGap(18, 18, 18)
                .addComponent(btRemover)
                .addGap(18, 18, 18)
                .addComponent(btEditar)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTipo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNome)
                            .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbAltura)
                        .addComponent(tfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPeso)
                            .addComponent(tfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfForca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbForca))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAtaque)
                            .addComponent(tfAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbDefesa)
                        .addComponent(tfDefesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbAgilidade))
                    .addComponent(tfAgilidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btRemover)
                    .addComponent(btEditar))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(440, 270, 300, 220);

        lbImagemFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ImagemPokedex.png"))); // NOI18N
        getContentPane().add(lbImagemFundo);
        lbImagemFundo.setBounds(0, -20, 761, 550);

        setSize(new java.awt.Dimension(777, 594));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTodosActionPerformed
        if(rbTodos.isSelected()){
            tfBuscar.setEnabled(false);
        }
    }//GEN-LAST:event_rbTodosActionPerformed

    private void rbNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNomeActionPerformed
        if(rbNome.isSelected()){
            tfBuscar.setEnabled(true);
        }
    }//GEN-LAST:event_rbNomeActionPerformed

    private void rbCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCodigoActionPerformed
        if(rbCodigo.isSelected()){
            tfBuscar.setEnabled(true);
        }
    }//GEN-LAST:event_rbCodigoActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        try{
            String nome = tfNome.getText();
            double peso = Double.parseDouble(tfPeso.getText());
            double altura = Double.parseDouble(tfAltura.getText());
            int ataque = Integer.parseInt(tfAtaque.getText());
            int forca = Integer.parseInt(tfForca.getText());
            int defesa = Integer.parseInt(tfDefesa.getText());
            int agilidade = Integer.parseInt(tfAgilidade.getText());
            if(cbTipo.getSelectedIndex() == 0){
                Aco pokemon = new Aco(nome, ETipo.AÇO, peso, altura, ataque, forca, defesa, agilidade, 1);
                pokemon.setCodigo(1);
                pokemon.ataqueEspecialAco();
                pokedex.inserirPokemon(pokemon);
                JOptionPane.showMessageDialog(null, "Pokemon Cadastrado!");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro");
        }
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        try{
            taInfo.setText("");
            if(rbTodos.isSelected()){
                List<Pokemon> lista = pokedex.imprimePokedex();
                for(Pokemon p : lista){
                    taInfo.append(p.toString() + "\n");
                }
            }else{
                if(rbNome.isSelected()){
                   Pokemon pokemon = pokedex.buscarPorNome(tfBuscar.getText());
                   taInfo.setText(pokemon.toString());
                }else if(rbCodigo.isSelected()){
                    Pokemon pokemon = pokedex.buscarPorCodigo(Integer.parseInt(tfBuscar.getText()));
                    taInfo.setText(pokemon.toString());
                }else if(rbTipo.isSelected()){
                    List<Pokemon> pokemon = pokedex.buscarPorTipo(tfBuscar.getText());
                    for(Pokemon p: pokemon){
                        taInfo.append(p.toString());
                    }
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro");
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void tfBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarActionPerformed

    private void rbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTipoActionPerformed
        if(rbTipo.isSelected()){
            tfBuscar.setEnabled(true);
        }
    }//GEN-LAST:event_rbTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPokedex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btcadastrar;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.ButtonGroup grSelecao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAgilidade;
    private javax.swing.JLabel lbAltura;
    private javax.swing.JLabel lbAtaque;
    private javax.swing.JLabel lbDefesa;
    private javax.swing.JLabel lbForca;
    private javax.swing.JLabel lbImagemFundo;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbPeso;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JRadioButton rbCodigo;
    private javax.swing.JRadioButton rbNome;
    private javax.swing.JRadioButton rbTipo;
    private javax.swing.JRadioButton rbTodos;
    private javax.swing.JTextArea taInfo;
    private javax.swing.JTextField tfAgilidade;
    private javax.swing.JTextField tfAltura;
    private javax.swing.JTextField tfAtaque;
    private javax.swing.JTextField tfBuscar;
    private javax.swing.JTextField tfDefesa;
    private javax.swing.JTextField tfForca;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPeso;
    // End of variables declaration//GEN-END:variables
}
