/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.Aco;
import classes.Agua;
import classes.Dragao;
import classes.Eletrico;
import classes.Fada;
import classes.Fantasma;
import classes.Fogo;
import classes.Gelo;
import classes.Grama;
import classes.Inseto;
import classes.Lutador;
import classes.Normal;
import classes.Pedra;
import classes.Pokedex;
import classes.Pokemon;
import classes.Psiquico;
import classes.Terra;
import classes.Veneno;
import classes.Voador;
import enums.ETipo;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis Guilherme
 */
public class TelaPokedex extends javax.swing.JFrame {

    private final Pokedex pokedex; //Objeto para acessar a Pokedex
    private Pokemon pkm; //Objeto para receber pokemon buscado
    private int cdg = 1; //Variável para controle de código
    
    public TelaPokedex() {
        initComponents();
        //btcadastrar.setContentAreaFilled(false);
        btRemover.setBackground(Color.RED);
        btEditar.setBackground(Color.YELLOW);
        btCadastrar.setBackground(Color.BLUE);
        btCadastrar.setForeground(Color.WHITE);
        btRemover.setForeground(Color.WHITE);
        btLimpar.setBackground(Color.WHITE);
        btBuscar.setBackground(Color.BLACK);
        btBuscar.setForeground(Color.WHITE);
        btLimpar.setBorderPainted(true);
        pokedex = new Pokedex();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grSelecao = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        taInfo = new javax.swing.JTextArea();
        rbTodos = new javax.swing.JRadioButton();
        rbNome = new javax.swing.JRadioButton();
        rbTipo = new javax.swing.JRadioButton();
        rbCodigo = new javax.swing.JRadioButton();
        btBuscar = new javax.swing.JButton();
        tfBuscar = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        lbTipo = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        tfNome = new javax.swing.JTextField();
        lbPeso = new javax.swing.JLabel();
        lbAltura = new javax.swing.JLabel();
        tfAltura = new javax.swing.JTextField();
        lbAtaque = new javax.swing.JLabel();
        tfAtaque = new javax.swing.JTextField();
        lbForca = new javax.swing.JLabel();
        tfForca = new javax.swing.JTextField();
        lbDefesa = new javax.swing.JLabel();
        tfDefesa = new javax.swing.JTextField();
        lbAgilidade = new javax.swing.JLabel();
        tfAgilidade = new javax.swing.JTextField();
        tfPeso = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        lbTelaFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pokédex");
        setMaximumSize(new java.awt.Dimension(761, 536));
        setPreferredSize(new java.awt.Dimension(761, 536));
        setResizable(false);
        getContentPane().setLayout(null);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        taInfo.setEditable(false);
        taInfo.setBackground(new java.awt.Color(51, 255, 51));
        taInfo.setColumns(20);
        taInfo.setRows(5);
        taInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane1.setViewportView(taInfo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(440, 90, 300, 170);

        grSelecao.add(rbTodos);
        rbTodos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbTodos.setSelected(true);
        rbTodos.setText("Todos");
        rbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTodosActionPerformed(evt);
            }
        });
        getContentPane().add(rbTodos);
        rbTodos.setBounds(670, 10, 59, 23);

        grSelecao.add(rbNome);
        rbNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbNome.setText("Nome");
        rbNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNomeActionPerformed(evt);
            }
        });
        getContentPane().add(rbNome);
        rbNome.setBounds(440, 10, 57, 23);

        grSelecao.add(rbTipo);
        rbTipo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbTipo.setText("Tipo");
        rbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTipoActionPerformed(evt);
            }
        });
        getContentPane().add(rbTipo);
        rbTipo.setBounds(600, 10, 49, 23);

        grSelecao.add(rbCodigo);
        rbCodigo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbCodigo.setText("Código");
        rbCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(rbCodigo);
        rbCodigo.setBounds(520, 10, 63, 23);

        btBuscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btBuscar);
        btBuscar.setBounds(660, 50, 80, 23);

        tfBuscar.setEnabled(false);
        tfBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(tfBuscar);
        tfBuscar.setBounds(440, 50, 210, 30);

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setBorder(null);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar);
        btLimpar.setBounds(240, 410, 100, 60);

        jPanel1.setBackground(new java.awt.Color(192, 13, 13));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        lbNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbNome.setText("Nome:");

        lbTipo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbTipo.setText("Tipo:");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AÇO", "ÁGUA", "DRAGÃO", "ELÉTRICO", "FADA", "FANTASMA", "FOGO", "GELO", "GRAMA", "INSETO", "LUTADOR", "NORMAL", "PEDRA", "PSÍQUICO", "TERRA", "VENENO", "VOADOR" }));
        cbTipo.setSelectedIndex(-1);

        lbPeso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbPeso.setText("Peso:");

        lbAltura.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbAltura.setText("Altura:");

        lbAtaque.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbAtaque.setText("Ataque:");

        lbForca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbForca.setText("Força:");

        lbDefesa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbDefesa.setText("Defesa:");

        lbAgilidade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbAgilidade.setText("Agilidade:");

        btCadastrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btRemover.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        btEditar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbDefesa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfDefesa, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAgilidade)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbPeso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbAtaque, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 14, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfAtaque, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                    .addComponent(tfPeso))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbForca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfForca, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfAgilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRemover)
                .addGap(18, 18, 18)
                .addComponent(btEditar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbTipo))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbNome)
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbAltura)
                        .addComponent(tfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPeso)
                            .addComponent(tfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfForca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbForca))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAtaque)
                            .addComponent(tfAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbDefesa)
                        .addComponent(tfDefesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbAgilidade))
                    .addComponent(tfAgilidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btRemover)
                    .addComponent(btEditar))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(440, 270, 300, 220);

        lbTelaFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTelaFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ImagemPokedex.png"))); // NOI18N
        getContentPane().add(lbTelaFundo);
        lbTelaFundo.setBounds(0, -20, 761, 550);

        setSize(new java.awt.Dimension(777, 594));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTodosActionPerformed
        if(rbTodos.isSelected()){
            tfBuscar.setEnabled(false);
        }
    }//GEN-LAST:event_rbTodosActionPerformed

    private void rbNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNomeActionPerformed
        if(rbNome.isSelected()){
            tfBuscar.setEnabled(true);
        }
    }//GEN-LAST:event_rbNomeActionPerformed

    private void rbCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCodigoActionPerformed
        if(rbCodigo.isSelected()){
            tfBuscar.setEnabled(true);
        }
    }//GEN-LAST:event_rbCodigoActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        try{
            String nome = tfNome.getText();
            if(pokedex.buscarPorNome(nome) == null){
                double peso = Double.parseDouble(tfPeso.getText());
                double altura = Double.parseDouble(tfAltura.getText());
                int ataque = Integer.parseInt(tfAtaque.getText());
                int forca = Integer.parseInt(tfForca.getText());
                int defesa = Integer.parseInt(tfDefesa.getText());
                int agilidade = Integer.parseInt(tfAgilidade.getText());
                switch (cbTipo.getSelectedIndex()) {
                    case 0:
                        {
                            Aco pokemon = new Aco(nome, ETipo.AÇO, peso, altura, ataque, forca, defesa, agilidade, cdg);
                            pokemon.ataqueEspecialAco();
                            pokedex.inserirPokemon(pokemon);
                            break;
                        }
                    case 1:
                        {
                            Agua pokemon = new Agua(nome, ETipo.ÁGUA, peso, altura, ataque, forca, defesa, agilidade, cdg);
                            pokemon.ataqueEspecialAgua();
                            pokedex.inserirPokemon(pokemon);
                            break;
                        }
                    case 2:
                        {
                            Dragao pokemon = new Dragao(nome, ETipo.DRAGÃO, peso, altura, ataque, forca, defesa, agilidade, cdg);
                            pokemon.ataqueEspecialDragao();
                            pokedex.inserirPokemon(pokemon);
                            break;
                        }
                    case 3:
                        {
                            Eletrico pokemon = new Eletrico(nome, ETipo.ELÉTRICO, peso, altura, ataque, forca, defesa, agilidade, cdg);
                            pokemon.ataqueEspecialEletrico();
                            pokedex.inserirPokemon(pokemon);
                            break;
                        }
                    case 4:
                        {
                            Fada pokemon = new Fada(nome, ETipo.FADA, peso, altura, ataque, forca, defesa, agilidade, cdg);
                            pokemon.ataqueEspecialFada();
                            pokedex.inserirPokemon(pokemon);
                            break;
                        }
                    case 5:
                        {
                            Fantasma pokemon = new Fantasma(nome, ETipo.FANTASMA, peso, altura, ataque, forca, defesa, agilidade, cdg);
                            pokemon.ataqueEspecialFantasma();
                            pokedex.inserirPokemon(pokemon);
                            break;
                        }
                    case 6:
                        {
                            Fogo pokemon = new Fogo(nome, ETipo.FOGO, peso, altura, ataque, forca, defesa, agilidade, cdg);
                            pokemon.ataqueEspecialFogo();
                            pokedex.inserirPokemon(pokemon);
                            break;
                        }
                    case 7:
                        {
                            Gelo pokemon = new Gelo(nome, ETipo.GELO, peso, altura, ataque, forca, defesa, agilidade, cdg);
                            pokemon.ataqueEspecialGelo();
                            pokedex.inserirPokemon(pokemon);
                            break;
                        }
                    case 8:
                        {
                            Grama pokemon = new Grama(nome, ETipo.GRAMA, peso, altura, ataque, forca, defesa, agilidade, cdg);
                            pokemon.ataqueEspecialGrama();
                            pokedex.inserirPokemon(pokemon);
                            break;
                        }
                    case 9:
                        {
                            Inseto pokemon = new Inseto(nome, ETipo.INSETO, peso, altura, ataque, forca, defesa, agilidade, cdg);
                            pokemon.ataqueEspecialInseto();
                            pokedex.inserirPokemon(pokemon);
                            break;
                        }
                    case 10:
                        {
                            Lutador pokemon = new Lutador(nome, ETipo.LUTADOR, peso, altura, ataque, forca, defesa, agilidade, cdg);
                            pokemon.ataqueEspecialLutador();                                                          
                            pokedex.inserirPokemon(pokemon);
                            break;
                        }
                    case 11:
                        {
                            Normal pokemon = new Normal(nome, ETipo.NORMAL, peso, altura, ataque, forca, defesa, agilidade, cdg);
                            pokemon.ataqueEspecialNormal();
                            pokedex.inserirPokemon(pokemon);
                            break;
                        }
                    case 12:
                        {
                            Pedra pokemon = new Pedra(nome, ETipo.PEDRA, peso, altura, ataque, forca, defesa, agilidade, cdg);
                            pokemon.ataqueEspecialPedra();
                            pokedex.inserirPokemon(pokemon);
                            break;
                        }
                    case 13:
                        {
                            Psiquico pokemon = new Psiquico(nome, ETipo.PSÍQUICO, peso, altura, ataque, forca, defesa, agilidade, cdg);
                            pokemon.ataqueEspecialPsiquico();
                            pokedex.inserirPokemon(pokemon);
                            break;
                        }
                    case 14:
                        {
                            Terra pokemon = new Terra(nome, ETipo.TERRA, peso, altura, ataque, forca, defesa, agilidade, cdg);
                            pokemon.ataqueEspecialTerra();
                            pokedex.inserirPokemon(pokemon);
                            break;
                        }
                    case 15:
                        {
                            Veneno pokemon = new Veneno(nome, ETipo.VENENO, peso, altura, ataque, forca, defesa, agilidade, cdg);
                            pokemon.ataqueEspecialVeneno();
                            pokedex.inserirPokemon(pokemon);
                            break;
                        }
                    case 16:
                        {
                            Voador pokemon = new Voador(nome, ETipo.VOADOR, peso, altura, ataque, forca, defesa, agilidade, cdg);
                            pokemon.ataqueEspecialVoador();
                            pokedex.inserirPokemon(pokemon);
                            break;
                        }
                    default:
                        break;
                }
                cdg++;
                JOptionPane.showMessageDialog(null, "Pokemon Cadastrado!");
            }else{
                JOptionPane.showMessageDialog(null, "Já existe pokemon cadastrado com esse nome!");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro");
        }
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        try{
            btEditar.setText("Editar");
            btRemover.setEnabled(false);
            btEditar.setEnabled(false);
            taInfo.setText("");
            if(rbTodos.isSelected()){
                List<Pokemon> lista = pokedex.imprimePokedex();
                for(Pokemon p : lista){
                    taInfo.append(p.toString() + "\n");
                }
            }else{
                if(rbNome.isSelected()){
                   pkm = pokedex.buscarPorNome(tfBuscar.getText());
                   if(pkm != null){
                        taInfo.setText(pkm.toString());
                        btRemover.setEnabled(true);
                        btEditar.setEnabled(true);
                   }
                }else if(rbCodigo.isSelected()){
                    pkm = pokedex.buscarPorCodigo(Integer.parseInt(tfBuscar.getText()));
                    if(pkm != null){
                        taInfo.setText(pkm.toString());
                        btRemover.setEnabled(true);
                        btEditar.setEnabled(true);
                    }
                }else if(rbTipo.isSelected()){
                    List<Pokemon> pokemon = pokedex.buscarPorTipo(tfBuscar.getText());
                    for(Pokemon p: pokemon){
                        taInfo.append(p.toString());
                    }
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro");
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void tfBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBuscarActionPerformed

    private void rbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTipoActionPerformed
        if(rbTipo.isSelected()){
            tfBuscar.setEnabled(true);
        }
    }//GEN-LAST:event_rbTipoActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        try{
            pokedex.removePokemon(pkm.getNome());
            JOptionPane.showMessageDialog(null, "Pokemon removido com sucesso!");
            taInfo.setText("");
            btRemover.setEnabled(false);
            btEditar.setEnabled(false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro");
        }
    }//GEN-LAST:event_btRemoverActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        btCadastrar.setEnabled(false);
        btRemover.setEnabled(false);
        try{
            if(btEditar.getText().equals("Editar")){
            tfNome.setText(pkm.getNome());
            tfPeso.setText(Double.toString(pkm.getPeso()));
            tfAtaque.setText(Integer.toString(pkm.getAtaque()));
            tfDefesa.setText(Integer.toString(pkm.getDefesa()));
            tfAltura.setText(Double.toString(pkm.getAltura()));
            tfForca.setText(Integer.toString(pkm.getForca()));
            tfAgilidade.setText(Integer.toString(pkm.getAgilidade()));
            cbTipo.setSelectedItem(pkm.getTipo().toString());
            btEditar.setText("Salvar");
            btEditar.setBackground(Color.GREEN);
            }else if(btEditar.getText().equals("Salvar")){
                String nome = tfNome.getText();
                if((pokedex.buscarPorNome(nome) != null) && (!pkm.getNome().equals(nome))){
                    JOptionPane.showMessageDialog(null, "Já existe pokemon cadastrado com esse nome!");
                }
                else{
                    pkm.setNome(tfNome.getText());
                    pkm.setAgilidade(Integer.parseInt(tfAgilidade.getText()));
                    pkm.setAltura(Double.parseDouble(tfAltura.getText()));
                    pkm.setAtaque(Integer.parseInt(tfAtaque.getText()));
                    pkm.setDefesa(Integer.parseInt(tfDefesa.getText()));
                    pkm.setForca(Integer.parseInt(tfForca.getText()));
                    pkm.setPeso(Double.parseDouble(tfPeso.getText()));
                    pkm.setTipo(retornaTipo(cbTipo.getSelectedItem().toString()));
                    pokedex.editarPokemon(pkm);
                    JOptionPane.showMessageDialog(null, "Alteração salva com sucesso!");
                    btEditar.setText("Editar");
                    btEditar.setEnabled(false);
                    btCadastrar.setEnabled(true);
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erro" + e);
        }
    }//GEN-LAST:event_btEditarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        tfNome.setText("");
        tfAgilidade.setText("");
        tfAltura.setText("");
        tfAtaque.setText("");
        tfDefesa.setText("");
        tfForca.setText("");
        tfPeso.setText("");
        cbTipo.setSelectedIndex(-1);
    }//GEN-LAST:event_btLimparActionPerformed

   private ETipo retornaTipo(String tipo){
       ETipo t = null;
       switch(tipo){
           case "AÇO":
               t = ETipo.AÇO;
               break;
           case "ÁGUA":
               t = ETipo.ÁGUA;
               break;
           case "DRAGÃO":
               t = ETipo.DRAGÃO;
               break;
           case "ELÉTRICO":
               t = ETipo.ELÉTRICO;
               break;
           case "FADA":
               t = ETipo.FADA;
               break;
           case "FANTASMA":
               t = ETipo.FANTASMA;
               break;
           case "FOGO":
               t = ETipo.FOGO;
               break;
           case "GELO":
               t = ETipo.GELO;
               break;
           case "GRAMA":
               t = ETipo.GRAMA;
               break;
           case "INSETO":
               t = ETipo.INSETO;
               break;
           case "LUTADOR":
               t = ETipo.LUTADOR;
               break;
           case "NORMAL":
               t = ETipo.NORMAL;
               break;
           case "PEDRA":
               t = ETipo.PEDRA;
               break;
           case "PSÍQUICO":
               t = ETipo.PSÍQUICO;
               break;
           case "TERRA":
               t = ETipo.TERRA;
               break;
           case "VENENO":
               t = ETipo.VENENO;
               break;
           case "VOADOR":
               t = ETipo.VOADOR;
               break;
       }
       return t;
   } 
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPokedex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btRemover;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.ButtonGroup grSelecao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAgilidade;
    private javax.swing.JLabel lbAltura;
    private javax.swing.JLabel lbAtaque;
    private javax.swing.JLabel lbDefesa;
    private javax.swing.JLabel lbForca;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbPeso;
    private javax.swing.JLabel lbTelaFundo;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JRadioButton rbCodigo;
    private javax.swing.JRadioButton rbNome;
    private javax.swing.JRadioButton rbTipo;
    private javax.swing.JRadioButton rbTodos;
    private javax.swing.JTextArea taInfo;
    private javax.swing.JTextField tfAgilidade;
    private javax.swing.JTextField tfAltura;
    private javax.swing.JTextField tfAtaque;
    private javax.swing.JTextField tfBuscar;
    private javax.swing.JTextField tfDefesa;
    private javax.swing.JTextField tfForca;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPeso;
    // End of variables declaration//GEN-END:variables
}
